# Bazarr connection settings
Address: <bazarr_address>
Port: <port>
Protocol: http
ApiToken: <Bazarr_api_token>

# Scheduling settings (optional)
Schedule:
  # Enable scheduled runs
  Enabled: true
  
  # What to sync
  SyncMovies: true
  SyncShows: true
  
  # Schedule using cron expression
  # Examples:
  # "0 1 * * 0" - Every Sunday at 1:00 AM
  # "0 2 * * *" - Every day at 2:00 AM
  # "0 3 * * 1,3,5" - Every Monday, Wednesday, Friday at 3:00 AM
  # "0 */6 * * *" - Every 6 hours
  CronExpression: "0 1 * * 0"
  
  # Timezone (e.g., "America/Chicago", "UTC", "Europe/London")
  Timezone: "America/Chicago"

# Cache settings (optional)
Cache:
  # Enable cache to skip already synced subtitles
  Enabled: true
  # Cache file locations (relative to working directory)
  MoviesCache: "/config/movies-cache"
  ShowsCache: "/config/shows-cache"

# Sync options (optional)
SyncOptions:
  # Use Golden Section Search algorithm
  GoldenSection: false
  # Don't try to fix framerate issues
  NoFramerateFix: true