project_name: bazarr-sync

before:
  hooks:
    - go mod tidy

builds:
  - id: bazarr-sync
    main: ./cmd/bazarr-sync/
    binary: bazarr-sync
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64

archives:
  - id: bazarr-sync
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - example/config.yaml

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  groups:
    - title: 'Features'
      regexp: '^.*feat[(\\w)]*:+.*$'
      order: 0
    - title: 'Bug fixes'
      regexp: '^.*fix[(\\w)]*:+.*$'
      order: 1
    - title: 'Others'
      order: 999

release:
  draft: false
  prerelease: auto